name: Run GTests Sequentially

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install dependencies
        run: sudo apt-get install -y cmake g++

      - name: Install Valgrind
        run: sudo apt-get install -y valgrind

      - name: Download and Install Google Test
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          mkdir build
          cd build
          cmake ..
          make
          sudo cp lib/*.a /usr/lib
          cd ../..

      - name: Configure Project
        run: cmake -B build -S .

      - name: Build Project
        run: cmake --build build

      # MatrixTest
      - name: Run MatrixTest normally
        run: ./build/MatrixTest

      - name: Run MatrixTest with Valgrind
        run: valgrind --leak-check=full --error-exitcode=1 ./build/MatrixTest

      # QRTest
      - name: Run QRTest normally
        run: ./build/QRTest

      - name: Run QRTest with Valgrind
        run: valgrind --leak-check=full --error-exitcode=1 ./build/QRTest

      # QRPerformanceTest
      - name: Run QRPerformanceTest normally
        run: ./build/QRPerformanceTest

      - name: Run QRPerformanceTest with Valgrind
        run: valgrind --leak-check=full --error-exitcode=1 ./build/QRPerformanceTest

      # FunctionTest
      - name: Run FunctionTest normally
        run: ./build/FunctionTest

      - name: Run FunctionTest with Valgrind
        run: valgrind --leak-check=full --error-exitcode=1 ./build/FunctionTest

      # ErrorFunctionTest
      - name: Run ErrorFunctionTest normally
        run: ./build/ErrorFunctionTest

      - name: Run ErrorFunctionTest with Valgrind
        run: valgrind --leak-check=full --error-exitcode=1 ./build/ErrorFunctionTest

      # OptimizationTaskTest
      - name: Run OptimizationTaskTest normally
        run: ./build/OptimizationTaskTest

      - name: Run OptimizationTaskTest with Valgrind
        run: valgrind --leak-check=full --error-exitcode=1 ./build/OptimizationTaskTest

      # LSMTaskTest
      - name: Run LSMTaskTest normally
        run: ./build/LSMTaskTest

      - name: Run LSMTaskTest with Valgrind
        run: valgrind --leak-check=full --error-exitcode=1 ./build/LSMTaskTest

      # GradientOptimizerTest
      - name: Run GradientOptimizerTest normally
        run: ./build/GradientOptimizerTest

      - name: Run GradientOptimizerTest with Valgrind
        run: valgrind --leak-check=full --error-exitcode=1 ./build/GradientOptimizerTest

      # NewtonGaussSolverTests
      - name: Run NewtonGaussSolverTests normally
        run: ./build/NewtonGaussSolverTests

      - name: Run NewtonGaussSolverTests with Valgrind
        run: valgrind --leak-check=full --error-exitcode=1 ./build/NewtonGaussSolverTests

      # NewtonOptimizerTest
      - name: Run NewtonOptimizerTest normally
        run: ./build/NewtonOptimizerTest

      - name: Run NewtonOptimizerTest with Valgrind
        run: valgrind --leak-check=full --error-exitcode=1 ./build/NewtonOptimizerTest

      # LMTest
      - name: Run LMTest normally
        run: ./build/LMTest

      - name: Run LMTest with Valgrind
        run: valgrind --leak-check=full --error-exitcode=1 ./build/LMTest

      # LMTestWithOurMatrix
      - name: Run LMTestWithOurMatrix normally
        run: ./build/LMTestWithOurMatrix

      - name: Run LMTestWithOurMatrix with Valgrind
        run: valgrind --leak-check=full --error-exitcode=1 ./build/LMTestWithOurMatrix

      # SimpleGraph
      - name: Run SimpleGraph normally
        run: ./build/SimpleGraph

      - name: Run SimpleGraph with Valgrind
        run: valgrind --leak-check=full --error-exitcode=1 ./build/SimpleGraph
