name: Run GTests Sequentially

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [
          "MatrixTest",
          "QRTest",
          "QRPerformanceTest",
          "FunctionTest",
          "ErrorFunctionTest",
          "OptimizationTaskTest",
          "LSMTaskTest",
          "GradientOptimizerTest",
          "NewtonGaussSolverTests",
          "NewtonOptimizerTest",
          "LMTest",
          "LMTestWithOurMatrix",
          "SimpleGraph"
        ]
        valgrind: [false, true]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install dependencies
        run: sudo apt-get install -y cmake g++ valgrind

      - name: Download and Install Google Test
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          mkdir build
          cd build
          cmake ..
          make
          sudo cp lib/*.a /usr/lib
          cd ../..

      - name: Configure Project
        run: cmake -B build -S .

      - name: Build Project
        run: cmake --build build

      - name: Run ${{ matrix.test }} normally
        if: ${{ matrix.valgrind == 'false' }}
        run: ./build/${{ matrix.test }}

      - name: Run ${{ matrix.test }} with Valgrind
        if: ${{ matrix.valgrind == 'true' }}
        run: valgrind --leak-check=full --error-exitcode=1 ./build/${{ matrix.test }}
